### ISSUE TITLE
calculation of actual evapotranspiration (et_act): same output as et_pot

### ISSUE THREAD

**Issue by juliuseberhard** [tpilz/echse_engines#2]
When calculating actual evapotranspiration with Penman-Monteith or Shuttleworth-Wallace, the output is suspiciously similar to potential evapotranspiration.
I assume that in file ./processes/hydro/evap/et_act.h, lines 317 and 387:
`return(et_penmon(lambda,delta,H_net,soilheat,rho_air,ez_0,ez,gamma,r_c,r_a));`
`return(et_sw(lambda,delta,H_net,H_soil,totalheat,soilheat,rho_air,ez_0,ez,gamma,r_c,r_ca,r_ss,r_sa,r_aa));`
should read
`etp = et_penmon(lambda,delta,H_net,soilheat,rho_air,ez_0,ez,gamma,r_c,r_a);`
`etp = et_sw(lambda,delta,H_net,H_soil,totalheat,soilheat,rho_air,ez_0,ez,gamma,r_c,r_ca,r_ss,r_sa,r_aa);`

grüße, julius

**Comment by tpilz** [comment]
No, it is correct as it is as the current soil moisture state is included in the PM and SW approaches directly via the resistance parameterisation, i.e., the function et_act() should return the results of et_penmon() and et_sw() immediately. Only for other approaches, calculating first potential ET and then the actual ET later on based on a soil moisture degradation factor, the function shall return at the end of the function definition (line 397).

When the results of et_pot() and et_act() for the SW and PM approaches are the same, possible reasons could be _either_ an imperfect consideration of soil moisture state via the resistance (e.g., because of improper resistance calculation) _or_ errors/uncertainties in the given soil parameters. Regarding the former, I am still searching for better solutions ...
